### ISSUE TITLE
Add citation() 

### ISSUE THREAD

**Issue by ericward-noaa** [DFO-NOAA-Pacific/surveyjoin#11]
Like other packages we’d have a citation for the package – but this’d be a good place to have citations for individual datasets / metadata, maybe not as in depth as get_survey_metadata

Add Zenodo DOI

**Comment by Lewis-Barnett-NOAA** [comment]
.bib for Alaska surveys can be found [here](https://github.com/afsc-gap-products/citations)

**Comment by ericward-noaa** [comment]
Done -- DOI created, and more citation information added to Readme
