### ISSUE TITLE
Add official survey shapefiles of boundaries, strata and design grids

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [DFO-NOAA-Pacific/surveyjoin#17]
And create function to read in shapefiles and create a unified spatial object (even with different grid resolutions)
-Lat and long vertices or centroids… and suggested UTMs (save good local UTM columns too)

Also potentially add prediction grids?

**Comment by ericward-noaa** [comment]
I included a get_shapefiles() function that returns URLs of the shapefiles. Decision points are (1) whether to include prediction grids in the package or link to where they are, and (2) whether to add UTMs

**Comment by ericward-noaa** [comment]
Prediction grids here: https://github.com/DFO-NOAA-Pacific/surveyjoin/commit/b7e7be44d9ab8594dbbd812702f1a64d1aa1d7f5
