### ISSUE TITLE
Stop storing as data objects in R package / link via Google Drive

### ISSUE THREAD

**Issue by ericward-noaa** [DFO-NOAA-Pacific/surveyjoin#2]
* Will test shared google drive as option
* This is a temporary fix until a more permanent caching solution is established

**Comment by seananderson** [comment]
Early on, run https://rtyley.github.io/bfg-repo-cleaner/ to remove the existing large files (everyone needs to clone a fresh copy after).

**Comment by ericward-noaa** [comment]
Ran this, deleting all history of nwfsc_haul.rda / nwfsc_catch.rda, afsc.rda

java -jar bfg.jar --delete-files nwfsc_catch.rda surveyjoin.git
java -jar bfg.jar --delete-files nwfsc_haul.rda surveyjoin.git
java -jar bfg.jar --delete-files nwfsc_afsc.rda surveyjoin.git
git reflog expire --expire=now --all && git gc --prune=now --aggressive

**Comment by ericward-noaa** [comment]
Example of using 'googledrive' is here; confirmed it works with authentication on the shared folder:

https://github.com/DFO-NOAA-Pacific/surveyjoin/blob/main/data-raw/googledrive_example.R
