### ISSUE TITLE
Prediction grids

### ISSUE THREAD

**Issue by ericward-noaa** [DFO-NOAA-Pacific/surveyjoin#20]
Some are linked ('pbs' in gfplots, 'nwfsc' in 'pfmc-assess'). Include with package? Other?

**Comment by seananderson** [comment]
Longterm I plan to move them (PBS synoptic trawl grids) here:
https://github.com/pbs-assess/gfdata/tree/master/data
They are currently here:
https://github.com/pbs-assess/gfplot/tree/master/data
(and are probably already slightly out of date)

gfdata is a light enough package we could possibly import from there.

**Comment by ericward-noaa** [comment]
https://github.com/DFO-NOAA-Pacific/surveyjoin/commit/b7e7be44d9ab8594dbbd812702f1a64d1aa1d7f5
