### ISSUE TITLE
Add documentation for default arguments of `get_data()`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [DFO-NOAA-Pacific/surveyjoin#28]
There are a lot of `NULL` arguments that are default in `get_data()` but they are not documented in the arguments in the roxygen at the top of the file. For example, if `region = NULL` does that mean you get data for all regions?
https://github.com/DFO-NOAA-Pacific/surveyjoin/blob/125e2f84de8c165daf6ebe0229c5a280c58371eb/R/get_data.R#L49

**Comment by ericward-noaa** [comment]
https://github.com/DFO-NOAA-Pacific/surveyjoin/commit/f1a25192aa2532004c7a3a68f793563fcf28432b
