### ISSUE TITLE
Include species dictionary (ITIS)

### ISSUE THREAD

**Issue by ericward-noaa** [DFO-NOAA-Pacific/surveyjoin#3]
Using taxize, create a dictionary that includes
* itis
* common name
* species name

For species complexes (e.g. vermillion/sunset rockfish) concatenate the itis id

**Comment by Lewis-Barnett-NOAA** [comment]
Reviewing progress on this from the AFSC side, @EmilyMarkowitz-NOAA has made great headway toward assigning ITIS codes for most of our records (https://github.com/afsc-gap-products/gap_public_data/blob/main/code/find_taxize_species_codes.R), however there are many taxa that have 0 or multiple matches in ITIS that need to be painstakingly resolved. Some of these have been resolved already by assigning the most appropriate ITIS code (lines 195-279 in linked code above), but it appears that we don't have the person-time to check the remaining problem taxa.

Seems like the cleanest thing to do at this point would be to filter out those without a resolved ITIS? Some of the complexes would be included but likely not all.

Another consideration is that we may need to do some work to ensure that we are assigning the same ITIS codes for higher taxonomic groups among regions.
