### ISSUE TITLE
Error in cache_data()

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [DFO-NOAA-Pacific/surveyjoin#42]
I have tried a few different times across different computers over the last month to run the `cache_data()` function unsuccessfully.  The error I am getting is: 

> cache_data()
Is it OK to cache OAuth access credentials in the folder C:/Users/CHANTE~1.WET/AppData/Local/gargle/gargle/Cache between R sessions?
1: Yes
2: No
Selection: 1
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in `map()`:
ℹ In index: 1.
Caused by error in `do_paginated_request()`:
! Client error: (403) Forbidden
Request had insufficient authentication scopes.
PERMISSION_DENIED
• message: Insufficient Permission
• domain: global
• reason: insufficientPermissions
Run `rlang::last_trace()` to see where the error occurred.
✖ Downloading nwfsc-catch.rds [25.8s]

@kellijohnson-NOAA and I tried to debug this issue together and were unable to determine the exact problem.  The folder in AppData that is created is present but the cached data files are not downloaded.  This function worked for Kelli back in January.  I suspect that I am missing something on my computer that is needed for caching the data.  Do you have any suggestions based on the above error message?

**Comment by ericward-noaa** [comment]
I think this is working now -- I just did some cleaning / rebuilding of the data on Google Drive
