### ISSUE TITLE
Assemble metadata for each survey

### ISSUE THREAD

**Issue by ericward-noaa** [DFO-NOAA-Pacific/surveyjoin#5]
(see ‘User-facing functions’ in Google doc) 

Each survey has an existing paragraph that can be returned -- along with a timestamp (date or version number)

**Comment by ericward-noaa** [comment]
As part of this, link to shapefiles describing the domain for each survey. This is in nwfscSurvey -- but will vary by survey/region

**Comment by ericward-noaa** [comment]
Adding a function 
get_survey_metadata(survey = …)
* returns ~1 paragraph description and link to data and reports and references for citation

**Comment by BridgetFerriss** [comment]
I started an AFSC BTS description in our Google Share[ folder [here]](url)(https://docs.google.com/document/d/1qi4EaoNa65219RzFEmqZRBWzMXJM8jn3HTcBQs-0q_g/edit). Considering this a starting point and open to any thoughts on length/depth/breadth/format. Feel free to edit directly. I also don't have a good link to BTS shapefiles as recommended by Eric above.

**Comment by Lewis-Barnett-NOAA** [comment]
Thanks @BridgetFerriss, I added links to public data portal, column-level metadata, and some other snippets to the doc. I'll chip away at the descriptions for surveys other than the GOA, assuming that this is the style we want to use.

**Comment by Curt-Whitmire-NOAA** [comment]
Thanks Bridget and Lewis for making progress on this. I haven't forgotten
about my part of the task, in creating some metadata for the West Coast
Groundfish Bottom Trawl Survey. I'm up against a deadline next week to get
data to our stock assessment scientists. After that, I should be able to
work on other tasks like this one.

Best...

Curt Whitmire (he/his)

Information Technology Specialist, Northwest Fisheries Science Center

NOAA Fisheries | U.S. Department of Commerce

Office: (831) 583-8554

www.fisheries.noaa.gov

**Comment by Curt-Whitmire-NOAA** [comment]
I created a survey [description](https://docs.google.com/document/d/19jTIqAdM0kkGdSNDqkdEStIB6jqlFvcQ6B-HEa3SZNI/edit?usp=sharing) for the NWFSC West Coast Groundfish Bottom Trawl Survey. 
@BridgetFerriss @Lewis-Barnett-NOAA I based my description largely on your format, so it should look very similar. I hope that was ok.

**Comment by ericward-noaa** [comment]
These are great. Still need to get a description / link for PBS data. Decision points would be where to put these within the package. Could be included here, as a Readme. Or as vignettes in the package. Other?

**Comment by seananderson** [comment]
For PBS trawl data, the best short descriptions and links are probably here:
https://search.open.canada.ca/opendata/?sort=metadata_modified+desc&search_text=synoptic+trawl&page=1
(individual links within that search)

We also have much longer annual reports if needed.
